### ISSUE TITLE
N25Q64 只能读，不能写

### ISSUE THREAD

**Issue by ruier** [armink/SFUD#10]
N25Q64 只能读，不能写，写完之后，读出来还是 0xFF，还是擦除后的状态。 
M25P32 板子上同样的程序，正常读写。
请问下，这种情况，可能是什么原因呢？

**Comment by armink** [comment]
估计开启写保护了吧。

- 1、确认下硬件 WP 引脚状态
- 2、尝试 sfud_read_status 读取并检查状态寄存器，确认状态不对后，一般写 0 即可，具体情况要看手册。

**Comment by armink** [comment]
问题解决了吗？

**Comment by ruier** [comment]
解决了，硬件有干扰
