### ISSUE TITLE
W25Q128写的时间太长了655秒

### ISSUE THREAD

**Issue by whj4674672** [armink/SFUD#11]
其他时间都正常

**Comment by armink** [comment]
差距也太大了，可以参考这里的测试数据：https://github.com/armink/SFUD/blob/master/docs/zh/benchmark.txt

上逻辑分析仪，检查你的 SPI 驱动有没有问题

**Comment by armink** [comment]
增大 RTT Tick 应该能解决你的问题

**Comment by whj4674672** [comment]
和其他人沟通已经发现这个问题了，已解决。我看了一下tick的意思，tick越大CPU执行这个任务的时间就会更多一些，所以能在合理的时间处理完，这样理解对吗？



在 2018-06-08 12:03:59，"朱天龙 (Armink)" <notifications@github.com> 写道：


增大 RTT Tick 应该能解决你的问题

**Comment by armink** [comment]
确切说是 Tick 越大，CPU 的调度频率会越高，所以 tick 的粒度也会越精细，处理一些延时操作也会更精准。
