### ISSUE TITLE
SST25VF016B在读写过程中单片机复位,会初始化失败

### ISSUE THREAD

**Issue by cld0815** [armink/SFUD#12]
可能是在AAI模式的原因.
解决方法:
在初始化读 JEDEC ID 之前增加命令 set_write_enabled(flash, false); // 退出 AAI 模式

**Comment by armink** [comment]
没看明白，是读写时未正常退出，重启前需执行 `set_write_enabled(flash, false);` 才能读取到 JEDEC ID ？
