### ISSUE TITLE
Error: Check SFDP signature error. It's must be 50444653h('S' 'F' 'D' 'P')

### ISSUE THREAD

**Issue by flightxgf** [armink/SFUD#15]
bsp：正点原子stm32f429-apollo  W25Q256
根据Readme进行了 no os 裸机移植，
出现如下问题,请问这中问题一般是 啥原因造成的呢？
[SFUD]Error: W25Q256 flash device is initialize fail.?
[SFUD](..\sfud\src\sfud.c:746) The flash device manufacturer ID is 0x9F, memory type ID is 0x90, capacity ID is 0x4D.
[SFUD](..\sfud\src\sfud_sfdp.c:122) Error: Check SFDP signature error. It's must be 50444653h('S' 'F' 'D' 'P').
[SFUD]Warning: Read SFDP parameter header information failed. The W25Q256 is not support JEDEC SFDP.
[SFUD]Warning: This flash device is not found or not support.

**Comment by flightxgf** [comment]
补充：
根据Redeme我在sfud_flash_def.h中 SFUD_FLASH_CHIP_TABLE中加入
{"W25Q256", SFUD_MF_ID_WINBOND, 0xEF, 0x18, 32L*1024L*1024L, SFUD_WM_PAGE_256B, 4096, 0x20}, 

sfud_port.c 选中了读写
sfud_cfg.h中添加如下：
enum {
    SFUD_W25Q256_DEVICE_INDEX = 0,
};

#define SFUD_FLASH_DEVICE_TABLE                                                \
{                                                                              \
    [SFUD_W25Q256_DEVICE_INDEX] = {.name = "W25Q256", .spi.name = "SPI5"},           \
}

mian.c中的调用是：
if (sfud_init() == SFUD_SUCCESS) {
        sfud_demo(0, sizeof(sfud_demo_test_buf), sfud_demo_test_buf);
    }

**Comment by armink** [comment]
检查 SPI 读写，感觉你这个读取出来的数据差异太大了。

正常的 W25Q256 的 JEDEC ID 信息是这样的：https://github.com/armink/SFUD/blob/master/sfud/inc/sfud_flash_def.h#L118

**Comment by flightxgf** [comment]
thanks

**Comment by armink** [comment]
问题解决了吗？解决了请关闭 issue
