### ISSUE TITLE
可以加一个SFUD_FLASH_CHIP_USER_TABLE在SFUD_FLASH_CHIP_TABLE定义里面

### ISSUE THREAD

**Issue by GeneKong** [armink/SFUD#18]
用户现在如果要自行添加一个SFUD被擦掉的芯片，需要修改flash_def.h头文件，可以加一个用户自定义的宏到配置里面，那样用户添加自定义芯片不用再修改库头文件了。

**Comment by armink** [comment]
- 1、每个 Flash 也可以独立指定对应的 Flash 配置，请查看首页文档：
![image](https://user-images.githubusercontent.com/1734686/44758720-99cb8300-ab68-11e8-8205-2d4f298da392.png)
- 2、既然是 SFUD 目前不支持的芯片，可否分享到 GitHub 上来，让更多的人去使用。

**Comment by GeneKong** [comment]
Thanks，那这个是无效问题，没看sfud_flash的数据结构
