### ISSUE TITLE
submodule管理

### ISSUE THREAD

**Issue by liquanqing** [armink/SFUD#26]
Hi，SFUD对于Submodule的管理遇到以下问题，
在移植SFUD时，遇到需要修改
sfud_cfg.h
sfud_flash_def.h
然而，为了不要影响的主代码，需要把inc和port文件夹单独拷贝一份到外部，然后外部指定头文件的包含路径为another/sfud_port/inc
然后git submodule add [SFUD_URL]后，发现在src中#include "../inc/sfud.h"依然包含的是自己的
sfud_flash_def.h，导致必须要修改sfud.c的头文件包含
所以，建议把sfud.c中的
#include "../inc/sfud.h"
改为
#include "sfud.h"
这样后面的工程只需要把inc和port拷贝一份，然后不影响到submodule的源码内容
把头文件路径包含到inc目录即可

**Comment by armink** [comment]
可以提交 pr 哈

sfud_sfdp.c 文件也可以一起改一下

**Comment by armink** [comment]
fixed in #27
