### ISSUE TITLE
请问有准备支持hal库吗

### ISSUE THREAD

**Issue by cctv180** [armink/SFUD#30]
请问有准备支持hal库吗，我看了示例里面都是标准库，现在新平台都hal库了搞不了

**Comment by armink** [comment]
暂时搞不了了，不过 RT-Thread 那边对于 STM32 Flash 都使用 HAL 有统一的驱动代码，你可以参考下

https://github.com/RT-Thread/rt-thread/tree/master/bsp/stm32/libraries/HAL_Drivers/drv_flash

**Comment by cctv180** [comment]
谢谢我去看看

**Comment by cctv180** [comment]
好的谢谢您啦我看看
