### ISSUE TITLE
ISSI 的 ID 有误?

### ISSUE THREAD

**Issue by cld0815** [armink/SFUD#31]
SFUD/sfud/inc/sfud_flash_def.h
#define SFUD_MF_ID_ISSI                                0xD5

http://www.issi.com/WW/pdf/25LP-WP080D-040D-020D.pdf
Page70
ID=9Dh

**Comment by armink** [comment]
目前还没有 ISSI flash 的支持，欢迎给本仓库提交相关 pr 哈

**Comment by armink** [comment]
搜搜这个 `0xD5` 确实在其他一些开源项目中也被用作 ISSI 的 ID  ，说明早期它的 ID 确实是这个 （[点击查看这里](https://github.com/jhcloos/flashrom/blob/master/flashchips.h#L454)）

而 `0x9D` 是制造商 PMC 的 ID ，应该是被 ISSI 收购了，所以继续使用自己的 ID ，商标是 ISSI ，这里也有说明 ：  https://github.com/jhcloos/flashrom/blob/master/flashchips.h#L554-L562

**Comment by armink** [comment]
如果没有问题 ，issue 就先关闭了
