### ISSUE TITLE
W25Q64FV不支持

### ISSUE THREAD

**Issue by Rainer-king** [armink/SFUD#32]
我按照readme里面的方法尝试了一下 ，依然显示有问题
 \ | /
- RT -     Thread Operating System
 / | \     4.0.1 build Mar 12 2020
 2006 - 2019 Copyright by rt-thread team
[SFUD] Warning: Read SFDP parameter header information failed. The W25Q64 is not support JEDEC SFDP.
[SFUD] Warning: This flash device is not found or not support.
[SFUD] Error: W25Q64 flash device is initialize fail.
ERROR: SPI flash probe failed by SPI device spi20.
msh />[31m[E/drv.sdio] wait completed timeout[0m

**Comment by armink** [comment]
这个片子挺常见的，建议检查硬件及驱动问题

**Comment by armink** [comment]
SFUD_USING_FLASH_INFO_TABLE 这个宏也确认开启下
