### ISSUE TITLE
AT45DB161的指令和sfud_def.h中的基本不同，实际不能支持？

### ISSUE THREAD

**Issue by bg2kaj** [armink/SFUD#33]
一方面指令部分有一些差异，如读取状态位，包括状态位的位置
另一方面代码对于AT45DB161的支持也不完整？如sfud_write函数，实际上AT45DB161的SFUD_WM_BYTE|SFUD_WM_DUAL_BUFFER写模式会使其落入else if (flash->chip.write_mode & SFUD_WM_DUAL_BUFFER)中，而此处为未完成功能：//TODO dual-buffer write mode

**Comment by armink** [comment]
AT45DB161 系列支持不完整，只支持 SFUD_WM_BYTE 模式，所以性能也偏弱

**Comment by bg2kaj** [comment]
我现在已经移植完了SFUD，并已经能够正确识别AT45DB161，但在初始化EasyFlash过程中报Error: Flash wait busy has an error.，在sfud_def.h中的命令字和AT45DB161的Datasheet中的描述也不同，如这个读忙状态的关键字，sfud_def.h中是SFUD_CMD_READ_STATUS_REGISTER                  0x05，而实际上应为0xD7。
再比如WRITE ENABLE和WRITE DISABLE，sfud_def.h中分别是0x06和0x04， 而AT45DB161只有Sector Protect，为3Dh + 2Ah + 7Fh + xxh的形式，因此SFUD例程函数sfud_demo也无法执行，报无法ERASE等。
我有没有什么办法，比如修改sfud_def.h中的命令字来使其支持AT45DB161，或者当前的SFUD无法支持AT45DB161？

**Comment by armink** [comment]
说实话，AT45DB161 没有太大的动力折腾了。这片子当年坑了太多人，还被 atmel 卖给 ADESTO了，价格也没有竞争力，用的人越来越少了

**Comment by bg2kaj** [comment]
OK 了解了
其实我是想使用EasyFlash，那我就使用自己的驱动来移植EasyFlash吧，谢谢作者的支持
