### ISSUE TITLE
建议不要把函数申明放在函数内，sourceinsight 等工具都没法跳转，不方便看代码。

### ISSUE THREAD

**Issue by qinpan1003** [armink/SFUD#35]
![image](https://user-images.githubusercontent.com/19748676/82170114-221e2880-98f6-11ea-83d2-a96f8ba58739.png)

**Comment by armink** [comment]
其实这样是为了软件代码的内聚性。可以考虑换个工具阅读代码哈，我一般常用，比如：RT-Thread Studio
