### ISSUE TITLE
SST25VF080B芯片支持

### ISSUE THREAD

**Issue by DeclanHuaChen** [armink/SFUD#37]
板子上用的这个芯片，自己加上了，分享一下
    {"SST25VF080B", SFUD_MF_ID_SST, 0x25, 0x8E, 1L * 1024L * 1024L, SFUD_WM_BYTE|SFUD_WM_AAI, 4096, 0x20},              \

**Comment by armink** [comment]
欢迎提交直接在 GitHub 上提交 PR ，这样代码可以直接合并进去了哈

**Comment by DeclanHuaChen** [comment]
好的 @armink
