### ISSUE TITLE
在IAR FOR STM8环境下的问题

### ISSUE THREAD

**Issue by slipperstree** [armink/SFUD#5]
形如 1<<24这种代码，虽然可以编译通过，但是会有警告提示位移超过上限。并且调试发现位移的结果是0。这会导致断言失败或条件判断错误。
目前我将上述代码改为 1L<<24可以解决问题。不知道有没有更好的办法？类似这种问题还出现在flash列表里的capacity项目，2*1024*1024在8位机环境下计算结果是0，所以同样需要在数字尾部添加L标识。还有demo函数里面的打印读取内容时，printf(%08x... 要改成 %08lx...，还有其他一些地方都是这个原因导致的。

**Comment by armink** [comment]
32bit 以下 cpu 确实会存在这个问题，你的修复方法就可以。非常感谢你的反馈~

欢迎发起 pull request

**Comment by slipperstree** [comment]
已经发起 pull request 请确认

**Comment by armink** [comment]
已合并
