### ISSUE TITLE
Release 

### ISSUE THREAD

**Issue by bethmal** [armink/SFUD#83]
@armink 您好，尽管中间改动过几次了，但是SFUD 的版本在头文件里一直没有变化，期待能定期发 Release 或者打上 Tag，这样在使用的时候能看到代码变化和对应的版本号。多谢！

**Comment by armink** [comment]
OK，刚正式发布的了第一个版本了 https://github.com/armink/SFUD/releases/tag/1.1.0

**Comment by bethmal** [comment]
多谢！
