### ISSUE TITLE
[FR]支持FastRead

### ISSUE THREAD

**Issue by kaidegit** [armink/SFUD#88]
有些Flash在Read模式和FastRead模式下速率差距有点大，SFUD似乎没做FastRead的支持，可能会导致某些Flash跑不到满速

![image](https://github.com/armink/SFUD/assets/60053077/e7c120f3-cc28-47f4-99b9-b3b90dd6fdab)
![image](https://github.com/armink/SFUD/assets/60053077/04866975-c500-4012-9226-9eebb7be2868)

**Comment by kaidegit** [comment]
https://github.com/armink/SFUD/pull/89

我简单地用宏实现了下切换，不过似乎JEDEC中能读到这个的信息，是否要根据JEDEC中的参数进行自动判断。如果用JEDEC的话FLASH_INFO_TABLE中估计得加点参数了。

**Comment by armink** [comment]
SFDP 中否有这个参数呢？如果有的话，那直接读取就更好了，这样也不用改 FLASH_INFO_TABLE 的

**Comment by kaidegit** [comment]
啊仔细看了下SFDP似乎只有多线读的时候的FastRead参数，单线的FastRead似乎没有

另外我说要在FLASH_INFO_TABLE加东西是因为如果从SFDP读了，不走JEDEC的设备也要有这个参所以要在table加😂

**Comment by armink** [comment]
我就怕不走 SFDP 的 FastRead 除了命令参数不一样，还有没有其他一些命令时序上的区别

如果基本都一样，那是可以考虑加到 FLASH_INFO_TABLE 里的

另外，未来更多的芯片其实是支持 SFDP 的，所以估计 SFDP 里如果能支持这个功能就更好了

**Comment by kaidegit** [comment]
PR还没合并，是我还需要补充什么吗

**Comment by armink** [comment]
FastRead 这套代码能兼容绝大多数的 NorFlash 吗？如果可以，能否大致给出已经确认的几款 Flash 型号，多谢~

作为通用的驱动，兼容性要求是需要优先考虑的

**Comment by kaidegit** [comment]
目前主要添加了使用0x0B指令作为快速读指令，并默认插入了一个dummy
我自己手上测试过的有W25Q32BV、XM25QH32CH、ZD25WQ80BT，这几个我当时应该看了手册没问题的
我检查了下其他的Flash的数据手册
P25Q40H
![image](https://github.com/armink/SFUD/assets/60053077/f4a32dc8-4dd8-4913-a816-c0c9fd4dd366)
![image](https://github.com/armink/SFUD/assets/60053077/bcb5877e-bd5a-41f7-a958-fcabd48272c3)
GD25Q64E
![image](https://github.com/armink/SFUD/assets/60053077/6fbe725c-ed0e-468c-b3fd-1bbf63e58494)
W25Q128JV
![image](https://github.com/armink/SFUD/assets/60053077/cfac00d1-849c-471f-a480-43425a79bbd5)
ZD25Q32C
![image](https://github.com/armink/SFUD/assets/60053077/7a455a1b-89e0-48f0-8069-3d639d2a496f)
BY25Q128AS
![image](https://github.com/armink/SFUD/assets/60053077/e4d27b6d-35c5-419f-980c-2a41d137fc47)
ZB25VQ128
![image](https://github.com/armink/SFUD/assets/60053077/396a966b-5cbe-4542-89c3-4a6a2e18faec)
IS25XP080D（这玩意的dummy似乎可以写寄存器配置，默认8bit对于SPI来说顶到了133M的上限，完全是足够的）
![image](https://github.com/armink/SFUD/assets/60053077/43d41c2a-dac1-4e81-a828-661060f8bc5d)
![image](https://github.com/armink/SFUD/assets/60053077/0e381d9f-6493-46ba-b520-318698bf5a39)
MX25L25645G（这玩意的dummy也可以配置的，不过SPI只能8bit）
![image](https://github.com/armink/SFUD/assets/60053077/c5b9588b-b65f-4308-b11f-aa2ddccea5dc)
![image](https://github.com/armink/SFUD/assets/60053077/1fc7618e-0c07-4644-90ce-86ef36c07c60)

**Comment by kaidegit** [comment]
ok
